AnimalType.find_or_create_by_name("Dog")
AnimalType.find_or_create_by_name("Cat")
AnimalType.find_or_create_by_name("Horse")
AnimalType.find_or_create_by_name("Rabbit")
AnimalType.find_or_create_by_name("Bird")
AnimalType.find_or_create_by_name("Reptile")
AnimalType.find_or_create_by_name("Other")
