  # create_table "animals", :force => true do |t|
  #   t.string   "microchip"
  #   t.string   "name"
  #   t.text     "description"
  #   t.string   "sex"
  #   t.string   "weight"
  #   t.date     "date_of_birth"
  #   t.boolean  "is_sterilized"
  #   t.string   "color"
  #   t.boolean  "is_mix_breed"
  #   t.string   "primary_breed"
  #   t.string   "secondary_breed"
  #   t.integer  "animal_type_id"
  #   t.integer  "animal_status_id"
  #   t.datetime "created_at"
  #   t.datetime "updated_at"
  #   t.integer  "shelter_id"
  #   t.date     "status_change_date"
  #   t.date     "arrival_date"
  #   t.integer  "hold_time"
  #   t.date     "euthanasia_date"
  #   t.integer  "accommodation_id"
  #   t.string   "size"
  #   t.boolean  "has_special_needs",  :default => false, :null => false
  #   t.text     "special_needs"
  #   t.string   "video_url"
  #   t.string   "age"
  # end
