s3_bucket: shelterexchange
s3_access_key_id: AKIAIAYOGZBGGRGY46DA
s3_secret_access_key: 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
s3_permission: public_read
s3_cache_control: public, max-age=<%= 365 * 24 * 60 * 60 %>
s3_upload_files:
  - public/stylesheets/global/**/**
  - public/design/**/**

package_assets:         on           # (on, off, always)
compress_assets:        on           # (on, off)
gzip_assets:            on           # (on, off)
javascript_compressor:  yui          # (yui, closure)
#embed_assets:           on          # (on, off, datauri)
#template_function:      _.template  # (defaults to the built-in micro-templating)
#package_path:           packages    # (defaults to assets)
# compressor_options:
  # compilation_level: ADVANCED_OPTIMIZATIONS


javascripts:
  app1:
    - public/javascripts/global/jquery.min.js
    - public/javascripts/global/jquery-ui.min.js
    - public/javascripts/global/jquery.ui.autocomplete.ext.js
    - public/javascripts/global/jquery.qtip.min.js
    - public/javascripts/global/jquery.blockUI.min.js
    - public/javascripts/global/jquery.jscroll.min.js
    - public/javascripts/global/modernizr.js
    - public/javascripts/global/forms.js
    - public/javascripts/global/date.js
    - public/javascripts/global/jquery_ujs.js
    - public/javascripts/app/*.js

  admin1:
    - public/javascripts/global/jquery.min.js
    - public/javascripts/global/jquery-ui.min.js
    - public/javascripts/global/jquery.ui.autocomplete.ext.js
    - public/javascripts/global/jquery.blockUI.min.js
    - public/javascripts/global/modernizr.js
    - public/javascripts/global/forms.js
    - public/javascripts/global/date.js
    - public/javascripts/global/jquery_ujs.js
    - public/javascripts/admin/*.js

  api1:
    - public/javascripts/global/jquery.min.js
    # - public/javascripts/global/jquery-ui.min.js
    # - public/javascripts/global/jquery.ui.autocomplete.ext.js
    # - public/javascripts/global/jquery.blockUI.min.js
    - public/javascripts/global/modernizr.js
    # - public/javascripts/global/forms.js
    - public/javascripts/global/date.js
    - public/javascripts/global/jquery_ujs.js
    - public/javascripts/api/*.js

  public1:
    - public/javascripts/global/jquery.min.js
    - public/javascripts/global/jquery-ui.min.js
    - public/javascripts/global/jquery.ui.autocomplete.ext.js
    - public/javascripts/global/jquery.blockUI.min.js
    - public/javascripts/global/jquery.nivo.slider.pack.js
    - public/javascripts/global/jquery.flip.min.js
    - public/javascripts/global/jquery.fancybox-1.3.4.pack.js
    - public/javascripts/global/jquery.jscroll.min.js
    - public/javascripts/global/modernizr.js
    # - public/javascripts/global/forms.js
    # - public/javascripts/global/date.js
    - public/javascripts/global/jquery_ujs.js
    - public/javascripts/public/*.js

  reports1:
    - public/javascripts/global/highcharts.js


stylesheets:
  app1:
    - public/stylesheets/global/**/*.css
    - public/stylesheets/app/common.css
    - public/stylesheets/app/controller.css
    
  app_login1:
    - public/stylesheets/global/**/*.css
    - public/stylesheets/app/login.css

  app_print1:
      - public/stylesheets/app/print.css
      
  admin1:
    - public/stylesheets/global/**/*.css
    - public/stylesheets/admin/common.css
    - public/stylesheets/admin/controller.css
  
  admin_login1:
    - public/stylesheets/global/**/*.css
    - public/stylesheets/admin/login.css
  
  api1:
    - public/stylesheets/global/**/*.css
    - public/stylesheets/api/common.css
    - public/stylesheets/api/controller.css
  
  public1:
    - public/stylesheets/global/**/*.css
    - public/stylesheets/public/common.css
    - public/stylesheets/public/controller.css
  
  # public_print1:
  #     - public/stylesheets/public/print.css
