s3_bucket: shelterexchange-staging
s3_access_key_id: AKIAIAYOGZBGGRGY46DA
s3_secret_access_key: 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
s3_permission: public_read
s3_cache_control: public, max-age=<%= 365 * 24 * 60 * 60 %>
s3_upload_files:
  - public/stylesheets/global/**/**
  - public/design/**/**
  - public/documents/**/**

package_assets:         on           # (on, off, always)
compress_assets:        on           # (on, off)
gzip_assets:            on           # (on, off)
javascript_compressor:  yui          # (yui, closure)


javascripts:
  app:
    - public/javascripts/global/jquery.min.js
    - public/javascripts/global/jquery-ui.min.js
    - public/javascripts/global/jquery.ui.autocomplete.ext.js
    - public/javascripts/global/jquery.qtip.min.js
    - public/javascripts/global/jquery.blockUI.min.js
    - public/javascripts/global/jquery.fancybox-1.3.4.pack.js
    - public/javascripts/global/jquery.jscroll.min.js
    - public/javascripts/global/jquery.placeholder.min.js
    - public/javascripts/global/tmpl.min.js
    - public/javascripts/global/jquery_fileupload/jquery.iframe-transport.js
    - public/javascripts/global/jquery_fileupload/jquery.fileupload.js
    - public/javascripts/global/jquery_fileupload/jquery.fileupload-ui.js
    - public/javascripts/global/jquery_fileupload/locale.js
    - public/javascripts/global/galleria-1.2.7.min.js    
    - public/javascripts/global/galleria.twelve.min.js
    - public/javascripts/global/modernizr.js
    - public/javascripts/global/date.js
    - public/javascripts/global/jquery_ujs.js
    - public/javascripts/shared/**/*.js
    - public/javascripts/app/**/*.js
    
  app_print:
    - public/javascripts/global/jquery.min.js
    - public/javascripts/global/modernizr.js
    - public/javascripts/shared/forms.js
    - public/javascripts/app/animals.js

  admin:
    - public/javascripts/global/jquery.min.js
    - public/javascripts/global/jquery-ui.min.js
    - public/javascripts/global/jquery.ui.autocomplete.ext.js
    - public/javascripts/global/jquery.blockUI.min.js
    - public/javascripts/global/modernizr.js
    - public/javascripts/global/date.js
    - public/javascripts/global/jquery_ujs.js
    - public/javascripts/shared/**/*.js
    - public/javascripts/admin/**/*.js

  api:
    - public/javascripts/global/jquery.min.js
    - public/javascripts/global/modernizr.js
    - public/javascripts/global/date.js
    - public/javascripts/global/jquery_ujs.js
    - public/javascripts/shared/**/*.js
    - public/javascripts/api/**/*.js

  public:
    - public/javascripts/global/jquery.min.js
    - public/javascripts/global/jquery-ui.min.js
    - public/javascripts/global/jquery.ui.autocomplete.ext.js
    - public/javascripts/global/jquery.blockUI.min.js
    - public/javascripts/global/jquery.nivo.slider.pack.js
    - public/javascripts/global/jquery.rss.min.js
    - public/javascripts/global/jquery.fancybox-1.3.4.pack.js
    - public/javascripts/global/jquery.jscroll.min.js
    - public/javascripts/global/jquery.placeholder.min.js
    - public/javascripts/global/galleria-1.2.7.min.js    
    - public/javascripts/global/galleria.twelve.min.js
    - public/javascripts/global/modernizr.js
    - public/javascripts/global/date.js
    - public/javascripts/global/jquery_ujs.js
    - public/javascripts/shared/**/*.js
    - public/javascripts/public/**/*.js

  reports:
    - public/javascripts/global/highcharts.js


stylesheets:
  app:
    - public/stylesheets/global/**/*.css 
    - public/stylesheets/app/common.css
    - public/stylesheets/app/controller.css
    - public/stylesheets/app/global_print.css

  app_login:
    - public/stylesheets/global/jquery-ui/*.css
    - public/stylesheets/global/wufoo/*.css
    - public/stylesheets/app/login/*.css

  app_print:
    - public/stylesheets/global/jquery-ui/*.css
    - public/stylesheets/global/wufoo/*.css    
    - public/stylesheets/app/print/*.css

  admin:
    - public/stylesheets/global/jquery-ui/*.css
    - public/stylesheets/global/wufoo/*.css
    - public/stylesheets/admin/common.css
    - public/stylesheets/admin/controller.css

  admin_login:
    - public/stylesheets/global/jquery-ui/*.css
    - public/stylesheets/global/wufoo/*.css
    - public/stylesheets/admin/login.css

  api:
    # - public/stylesheets/global/fancybox/*.css
    # - public/stylesheets/global/galleria/**/*.css
    - public/stylesheets/global/jquery-ui/*.css
    - public/stylesheets/global/wufoo/*.css  
    - public/stylesheets/api/common.css
    - public/stylesheets/api/controller.css

  public:  
    - public/stylesheets/global/fancybox/*.css
    - public/stylesheets/global/galleria/**/*.css
    - public/stylesheets/global/jquery-ui/*.css
    - public/stylesheets/global/nivo-slider/*.css
    - public/stylesheets/global/wufoo/*.css
    - public/stylesheets/public/common.css
    - public/stylesheets/public/controller.css

  public_popup:
    - public/stylesheets/global/jquery-ui/*.css
    - public/stylesheets/global/wufoo/*.css    
    - public/stylesheets/public/popup.css
    - public/stylesheets/public/controller.css
