development:
    adapter: mysql2
    database: shelterexchange_dev
    username: shelterexchange
    password: shelterexchange

test:
    adapter: mysql2
    database: shelterexchange_test
    username: shelterexchange
    password: shelterexchange

demo:
    adapter: mysql2
    database: shelterexchange_demo
    username: se_demo
    password: 
    pool: 5

staging:
    adapter: mysql2
    database: shelterexchange_staging
    username: se_staging
    password: 
    pool: 5

production:
    adapter: mysql2
    database: shelterexchange
    username: se_prod
    password: 
    pool: 20
