development:
    adapter: mysql2
    database: shelterexchange_dev
    username: shelterexchange
    password: shelterexchange

test:
    adapter: mysql
    database: shelterexchange_test
    username: shelterexchange
    password: shelterexchange
    socket: /Applications/MAMP/tmp/mysql/mysql.sock

demo:
    adapter: mysql2
    database: shelterexchange-demo
    username: se_demo
    password: 

staging:
    adapter: mysql2
    database: shelterexchange-staging
    username: se_staging
    password: 

production:
    adapter: mysql2
    database: shelterexchange
    username: se_prod
    password: 
