defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: shelterexchange
  password: shelterexchange
  host: localhost
  socket: /tmp/mysql.sock

development:
    <<: *defaults
    database: shelterexchange_dev

test:
    <<: *defaults
    database: shelterexchange_test

staging:
    <<: *defaults
    database: shelterexchange_staging

production:
    <<: *defaults
    database: shelterexchange
