# Engine Yard Cloud Deploy Options
# ------------------------------------------------
defaults:
  migrate: false
  migration_command: rake db:migrate
  precompile_assets: true
  copy_exclude:
    - .git
    - spec

# Environment specific options.
# ------------------------------------------------
environments:

  production:
    branch: production

  production_app:
    branch: production

  staging:
    branch: staging

  staging_app:
    branch: staging

