environments:
 shelter_exchange_app_production:
   branch: production
   migrate: false
   copy_exclude:
      - .git

 shelter_exchange_app_staging:
   branch: staging
   migrate: false
   copy_exclude:
       - .git
