# Engine Yard Cloud Deploy Options
# ------------------------------------------------
defaults:
  migrate: false
  migration_command: rake db:migrate
  precompile_assets: true
  copy_exclude:
    - .git
    - spec

# Environment specific options.
# ------------------------------------------------
environments:

  shelter_exchange_app_production:
    branch: production

  production_app:
    branch: production

  staging_app:
    branch: staging

