environments:
 shelter_exchange_app_production:
   branch: master 
   migrate: false
   copy_exclude:
      - .git
 
 shelter_exchange_app_staging:
   branch: master
   migrate: false
   copy_exclude:
       - .git
 
 shelter_exchange_app_demo:
   branch: master
   migrate: false
   copy_exclude:
     - .git


     