common: &common
    access_key_id: AKIAIAYOGZBGGRGY46DA
    secret_access_key: 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
    acl: public-read
  
development:
    <<: *common
    bucket: shelterexchange-development

test:
    <<: *common
    bucket: shelterexchange-test

staging:
    <<: *common
    bucket: shelterexchange-staging

demo:
    <<: *common
    bucket: shelterexchange-demo

production:
    <<: *common
    bucket: shelterexchange





