# -*- coding: utf-8 -*-

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)


def truncate_db_table(table)
      config = ActiveRecord::Base.configurations[Rails.env]
      ActiveRecord::Base.establish_connection
      case config["adapter"]
        when "mysql"
          ActiveRecord::Base.connection.execute("TRUNCATE #{table}")
        when "sqlite", "sqlite3"
          ActiveRecord::Base.connection.execute("DELETE FROM #{table}")
          ActiveRecord::Base.connection.execute("DELETE FROM sqlite_sequence where name='#{table}'")
          ActiveRecord::Base.connection.execute("VACUUM")
      end
end

#######################################################################################################################
#
#   Truncate All Database Tables data
#
#######################################################################################################################
truncate_db_table("animals")
truncate_db_table("animal_types")
truncate_db_table("animal_statuses")
truncate_db_table("breeds")
truncate_db_table("notes")
truncate_db_table("note_categories")
truncate_db_table("alerts")
truncate_db_table("alert_types")

#######################################################################################################################
#
#   AnimalType Create
#      Creates the AnimalType Categories so that we have a standard set of Animal Types
#
#######################################################################################################################
dog     = AnimalType.create( :name => "Dog" )
cat     = AnimalType.create( :name => "Cat" )
horse   = AnimalType.create( :name => "Horse" )
rabbit  = AnimalType.create( :name => "Rabbit" )
bird    = AnimalType.create( :name => "Bird" )
reptile = AnimalType.create( :name => "Reptile" )
other   = AnimalType.create( :name => "Other" )


#######################################################################################################################
#
#   AnimalStatus Create
#      Creates the AnimalStaus Categories so that we have a standard set of Statuses
#
#######################################################################################################################
AnimalStatus.create([
  { :name => "Available for Adoption" },
  { :name => "Adopted" },
  { :name => "Foster Care" },
  { :name => "Deceased" }
])

#######################################################################################################################
#
#   Breed Create
#      Creates the AnimalType Categories so that we have a standard set of Animal Types
#
#######################################################################################################################

### DOG ###############################################################################################################
Breed.create([
 { :animal_type_id => dog.id, :name => "Affenpinscher" },
 { :animal_type_id => dog.id, :name => "Afghan Hound" },
 { :animal_type_id => dog.id, :name => "Africanis" },
 { :animal_type_id => dog.id, :name => "Aidi" },
 { :animal_type_id => dog.id, :name => "Airedale Terrier" },
 { :animal_type_id => dog.id, :name => "Akbash Dog" },
 { :animal_type_id => dog.id, :name => "Akita Inu" },
 { :animal_type_id => dog.id, :name => "Alangu Mastiff" },
 { :animal_type_id => dog.id, :name => "Alano Español" },
 { :animal_type_id => dog.id, :name => "Alapaha Blue Blood Bulldog" },
 { :animal_type_id => dog.id, :name => "Alaskan Klee Kai" },
 { :animal_type_id => dog.id, :name => "Alaskan Malamute" },
 { :animal_type_id => dog.id, :name => "Alaunt" },
 { :animal_type_id => dog.id, :name => "Alopekis" },
 { :animal_type_id => dog.id, :name => "Alpine Dachsbracke" },
 { :animal_type_id => dog.id, :name => "Alsatian Shepalute" },
 { :animal_type_id => dog.id, :name => "American Akita" },
 { :animal_type_id => dog.id, :name => "American Bulldog" },
 { :animal_type_id => dog.id, :name => "American Bully" },
 { :animal_type_id => dog.id, :name => "American Cocker Spaniel" },
 { :animal_type_id => dog.id, :name => "American Eskimo Dog" },
 { :animal_type_id => dog.id, :name => "American Foxhound" },
 { :animal_type_id => dog.id, :name => "American Hairless Terrier" },
 { :animal_type_id => dog.id, :name => "American Mastiff" },
 { :animal_type_id => dog.id, :name => "American Pit Bull Terrier" },
 { :animal_type_id => dog.id, :name => "American Staffordshire Terrier" },
 { :animal_type_id => dog.id, :name => "American Water Spaniel" },
 { :animal_type_id => dog.id, :name => "Anatolian Shepherd Dog" },
 { :animal_type_id => dog.id, :name => "Anglo-Français de Petite Vénerie" },
 { :animal_type_id => dog.id, :name => "Antebellum Bulldog" },
 { :animal_type_id => dog.id, :name => "Appenzeller Sennenhund" },
 { :animal_type_id => dog.id, :name => "Argentine Dogo" },
 { :animal_type_id => dog.id, :name => "Ariege Pointer" },
 { :animal_type_id => dog.id, :name => "Ariegeois" },
 { :animal_type_id => dog.id, :name => "Armant" },
 { :animal_type_id => dog.id, :name => "Armenian Gampr dog" },
 { :animal_type_id => dog.id, :name => "Artois Hound" },
 { :animal_type_id => dog.id, :name => "Australian Bulldog" },
 { :animal_type_id => dog.id, :name => "Australian Cattle Dog" },
 { :animal_type_id => dog.id, :name => "Australian Kelpie" },
 { :animal_type_id => dog.id, :name => "Australian Shepherd" },
 { :animal_type_id => dog.id, :name => "Australian Silky Terrier" },
 { :animal_type_id => dog.id, :name => "Australian Stumpy Tail Cattle Dog" },
 { :animal_type_id => dog.id, :name => "Australian Terrier" },
 { :animal_type_id => dog.id, :name => "Austrian Black and Tan Hound" },
 { :animal_type_id => dog.id, :name => "Austrian Pinscher" },
 { :animal_type_id => dog.id, :name => "Azawakh" },
 { :animal_type_id => dog.id, :name => "Bakharwal Dog" },
 { :animal_type_id => dog.id, :name => "Barbet" },
 { :animal_type_id => dog.id, :name => "Basenji" },
 { :animal_type_id => dog.id, :name => "Basque Shepherd Dog" },
 { :animal_type_id => dog.id, :name => "Basset Artésien Normand" },
 { :animal_type_id => dog.id, :name => "Basset Bleu de Gascogne" },
 { :animal_type_id => dog.id, :name => "Basset Fauve de Bretagne" },
 { :animal_type_id => dog.id, :name => "Grand Basset Griffon Vendéen" },
 { :animal_type_id => dog.id, :name => "Petit Basset Griffon Vendéen" },
 { :animal_type_id => dog.id, :name => "Basset Hound" },
 { :animal_type_id => dog.id, :name => "Bavarian Mountain Hound" },
 { :animal_type_id => dog.id, :name => "Beagle" },
 { :animal_type_id => dog.id, :name => "Beagle-Harrier" },
 { :animal_type_id => dog.id, :name => "Bearded Collie" },
 { :animal_type_id => dog.id, :name => "Beauceron" },
 { :animal_type_id => dog.id, :name => "Bedlington Terrier" },
 { :animal_type_id => dog.id, :name => "Belgian Shepherd Dog (Groenendael)" },
 { :animal_type_id => dog.id, :name => "Belgian Shepherd Dog (Laekenois)" },
 { :animal_type_id => dog.id, :name => "Belgian Shepherd Dog (Malinois)" },
 { :animal_type_id => dog.id, :name => "Belgian Shepherd (Tervuren)" },
 { :animal_type_id => dog.id, :name => "Bergamasco Shepherd" },
 { :animal_type_id => dog.id, :name => "Berger Blanc Suisse" },
 { :animal_type_id => dog.id, :name => "Berger Picard" },
 { :animal_type_id => dog.id, :name => "Berner Laufhund" },
 { :animal_type_id => dog.id, :name => "Bernese Mountain Dog" },
 { :animal_type_id => dog.id, :name => "Bichon Frisé" },
 { :animal_type_id => dog.id, :name => "Billy" },
 { :animal_type_id => dog.id, :name => "Bisben" },
 { :animal_type_id => dog.id, :name => "Black and Tan Coonhound" },
 { :animal_type_id => dog.id, :name => "Black and Tan Virginia Foxhound" },
 { :animal_type_id => dog.id, :name => "Bullenbeisser" },
 { :animal_type_id => dog.id, :name => "Black Norwegian Elkhound" },
 { :animal_type_id => dog.id, :name => "Black Russian Terrier" },
 { :animal_type_id => dog.id, :name => "Blackmouth Cur" },
 { :animal_type_id => dog.id, :name => "Grand Bleu de Gascogne" },
 { :animal_type_id => dog.id, :name => "Petit Bleu de Gascogne" },
 { :animal_type_id => dog.id, :name => "Bloodhound" },
 { :animal_type_id => dog.id, :name => "Blue Lacy" },
 { :animal_type_id => dog.id, :name => "Blue Paul Terrier" },
 { :animal_type_id => dog.id, :name => "Bluetick Coonhound" },
 { :animal_type_id => dog.id, :name => "Boerboel" },
 { :animal_type_id => dog.id, :name => "Bohemian Shepherd" },
 { :animal_type_id => dog.id, :name => "Bolognese" },
 { :animal_type_id => dog.id, :name => "Border Collie" },
 { :animal_type_id => dog.id, :name => "Border Terrier" },
 { :animal_type_id => dog.id, :name => "Borzoi" },
 { :animal_type_id => dog.id, :name => "Bosnian Coarse-haired Hound" },
 { :animal_type_id => dog.id, :name => "Boston Terrier" },
 { :animal_type_id => dog.id, :name => "Bouvier des Ardennes" },
 { :animal_type_id => dog.id, :name => "Bouvier des Flandres" },
 { :animal_type_id => dog.id, :name => "Boxer" },
 { :animal_type_id => dog.id, :name => "Boykin Spaniel" },
 { :animal_type_id => dog.id, :name => "Bracco Italiano" },
 { :animal_type_id => dog.id, :name => "Braque d'Auvergne" },
 { :animal_type_id => dog.id, :name => "Braque du Bourbonnais" },
 { :animal_type_id => dog.id, :name => "Braque du Puy" },
 { :animal_type_id => dog.id, :name => "Braque Francais" },
 { :animal_type_id => dog.id, :name => "Braque Saint-Germain" },
 { :animal_type_id => dog.id, :name => "Brazilian Terrier" },
 { :animal_type_id => dog.id, :name => "Briard" },
 { :animal_type_id => dog.id, :name => "Briquet Griffon Vendéen" },
 { :animal_type_id => dog.id, :name => "Brittany" },
 { :animal_type_id => dog.id, :name => "Broholmer" },
 { :animal_type_id => dog.id, :name => "Bruno Jura Hound" },
 { :animal_type_id => dog.id, :name => "Bucovina Shepherd Dog" },
 { :animal_type_id => dog.id, :name => "Bull and Terrier" },
 { :animal_type_id => dog.id, :name => "Bull Terrier" },
 { :animal_type_id => dog.id, :name => "Bull Terrier (Miniature)" },
 { :animal_type_id => dog.id, :name => "Bulldog" },
 { :animal_type_id => dog.id, :name => "Bullmastiff" },
 { :animal_type_id => dog.id, :name => "Bully Kutta" },
 { :animal_type_id => dog.id, :name => "Cairn Terrier" },
 { :animal_type_id => dog.id, :name => "Canaan Dog" },
 { :animal_type_id => dog.id, :name => "Canadian Eskimo Dog" },
 { :animal_type_id => dog.id, :name => "Canadian Pointer" },
 { :animal_type_id => dog.id, :name => "Cane Corso" },
 { :animal_type_id => dog.id, :name => "Cão da Serra de Aires" },
 { :animal_type_id => dog.id, :name => "Cão de Castro Laboreiro" },
 { :animal_type_id => dog.id, :name => "Cão Fila de São Miguel" },
 { :animal_type_id => dog.id, :name => "Carolina Dog" },
 { :animal_type_id => dog.id, :name => "Carpathian Shepherd Dog" },
 { :animal_type_id => dog.id, :name => "Catahoula Cur" },
 { :animal_type_id => dog.id, :name => "Catalan Sheepdog" },
 { :animal_type_id => dog.id, :name => "Caucasian Shepherd Dog" },
 { :animal_type_id => dog.id, :name => "Cavalier King Charles Spaniel" },
 { :animal_type_id => dog.id, :name => "Central Asian Shepherd Dog" },
 { :animal_type_id => dog.id, :name => "Cesky Fousek" },
 { :animal_type_id => dog.id, :name => "Cesky Terrier" },
 { :animal_type_id => dog.id, :name => "Chesapeake Bay Retriever" },
 { :animal_type_id => dog.id, :name => "Chien-gris" },
 { :animal_type_id => dog.id, :name => "Chien Français Blanc et Noir" },
 { :animal_type_id => dog.id, :name => "Chien Français Blanc et Orange" },
 { :animal_type_id => dog.id, :name => "Chien Français Tricolore" },
 { :animal_type_id => dog.id, :name => "Chihuahua" },
 { :animal_type_id => dog.id, :name => "Chilean Fox Terrier" },
 { :animal_type_id => dog.id, :name => "Chinese Chongqing Dog" },
 { :animal_type_id => dog.id, :name => "Chinese Crested Dog" },
 { :animal_type_id => dog.id, :name => "Chinese Imperial Dog" },
 { :animal_type_id => dog.id, :name => "Chinook" },
 { :animal_type_id => dog.id, :name => "Chippiparai" },
 { :animal_type_id => dog.id, :name => "Chow Chow" },
 { :animal_type_id => dog.id, :name => "Cimarrón Uruguayo" },
 { :animal_type_id => dog.id, :name => "Cierny Sery" },
 { :animal_type_id => dog.id, :name => "Cirneco dell'Etna" },
 { :animal_type_id => dog.id, :name => "Clumber Spaniel" },
 { :animal_type_id => dog.id, :name => "Rough Collie" },
 { :animal_type_id => dog.id, :name => "Smooth Collie" },
 { :animal_type_id => dog.id, :name => "Combai" },
 { :animal_type_id => dog.id, :name => "Cordoba Fighting Dog" },
 { :animal_type_id => dog.id, :name => "Coton de Tulear" },
 { :animal_type_id => dog.id, :name => "Cretan Hound" },
 { :animal_type_id => dog.id, :name => "Croatian Sheepdog" },
 { :animal_type_id => dog.id, :name => "Cumberland Sheepdog" },
 { :animal_type_id => dog.id, :name => "Curly Coated Retriever" },
 { :animal_type_id => dog.id, :name => "Czechoslovakian Wolfdog" },
 { :animal_type_id => dog.id, :name => "Dachshund" },
 { :animal_type_id => dog.id, :name => "Dalmatian" },
 { :animal_type_id => dog.id, :name => "Dandie Dinmont Terrier" },
 { :animal_type_id => dog.id, :name => "Danish Swedish Farmdog" },
 { :animal_type_id => dog.id, :name => "Doberman Pinscher" },
 { :animal_type_id => dog.id, :name => "Dogue de Bordeaux" },
 { :animal_type_id => dog.id, :name => "Dogo Cubano" },
 { :animal_type_id => dog.id, :name => "Dogo Guatemalteco" },
 { :animal_type_id => dog.id, :name => "Dogo Sardesco" },
 { :animal_type_id => dog.id, :name => "Drentse Patrijshond" },
 { :animal_type_id => dog.id, :name => "Drever" },
 { :animal_type_id => dog.id, :name => "Dunker" },
 { :animal_type_id => dog.id, :name => "Dutch Shepherd Dog" },
 { :animal_type_id => dog.id, :name => "Dutch Smoushond" },
 { :animal_type_id => dog.id, :name => "East-European Shepherd" },
 { :animal_type_id => dog.id, :name => "East Siberian Laika" },
 { :animal_type_id => dog.id, :name => "Elo" },
 { :animal_type_id => dog.id, :name => "English Cocker Spaniel" },
 { :animal_type_id => dog.id, :name => "English Coonhound" },
 { :animal_type_id => dog.id, :name => "English Foxhound" },
 { :animal_type_id => dog.id, :name => "English Mastiff" },
 { :animal_type_id => dog.id, :name => "English Pointer" },
 { :animal_type_id => dog.id, :name => "English Setter" },
 { :animal_type_id => dog.id, :name => "English Shepherd" },
 { :animal_type_id => dog.id, :name => "English Springer Spaniel" },
 { :animal_type_id => dog.id, :name => "English Toy Terrier (Black & Tan)" },
 { :animal_type_id => dog.id, :name => "English Water Spaniel" },
 { :animal_type_id => dog.id, :name => "English White Terrier" },
 { :animal_type_id => dog.id, :name => "Entlebucher Mountain Dog" },
 { :animal_type_id => dog.id, :name => "Épagneul Bleu de Picardie" },
 { :animal_type_id => dog.id, :name => "Estonian Hound" },
 { :animal_type_id => dog.id, :name => "Estrela Mountain Dog" },
 { :animal_type_id => dog.id, :name => "Eurasier" },
 { :animal_type_id => dog.id, :name => "Field Spaniel" },
 { :animal_type_id => dog.id, :name => "Fila Brasileiro" },
 { :animal_type_id => dog.id, :name => "Finnish Hound" },
 { :animal_type_id => dog.id, :name => "Finnish Lapphund" },
 { :animal_type_id => dog.id, :name => "Finnish Spitz" },
 { :animal_type_id => dog.id, :name => "Flat-Coated Retriever" },
 { :animal_type_id => dog.id, :name => "Formosan Mountain Dog" },
 { :animal_type_id => dog.id, :name => "Fox Terrier (Smooth)" },
 { :animal_type_id => dog.id, :name => "Wire Fox Terrier" },
 { :animal_type_id => dog.id, :name => "French Brittany" },
 { :animal_type_id => dog.id, :name => "French Bulldog" },
 { :animal_type_id => dog.id, :name => "French Spaniel" },
 { :animal_type_id => dog.id, :name => "Galgo Español" },
 { :animal_type_id => dog.id, :name => "German Longhaired Pointer" },
 { :animal_type_id => dog.id, :name => "German Pinscher" },
 { :animal_type_id => dog.id, :name => "German Shepherd Dog" },
 { :animal_type_id => dog.id, :name => "German Shorthaired Pointer" },
 { :animal_type_id => dog.id, :name => "German Spaniel" },
 { :animal_type_id => dog.id, :name => "German Spitz" },
 { :animal_type_id => dog.id, :name => "German Wirehaired Pointer" },
 { :animal_type_id => dog.id, :name => "Giant Schnauzer" },
 { :animal_type_id => dog.id, :name => "Glen of Imaal Terrier" },
 { :animal_type_id => dog.id, :name => "Golden Retriever" },
 { :animal_type_id => dog.id, :name => "Gordon Setter" },
 { :animal_type_id => dog.id, :name => "Grand Anglo-Français Blanc et Noir" },
 { :animal_type_id => dog.id, :name => "Grand Anglo-Français Blanc et Orange" },
 { :animal_type_id => dog.id, :name => "Grand Anglo-Français Tricolore" },
 { :animal_type_id => dog.id, :name => "Grand Griffon Vendéen" },
 { :animal_type_id => dog.id, :name => "Gran Mastín de Borínquen" },
 { :animal_type_id => dog.id, :name => "Great Dane" },
 { :animal_type_id => dog.id, :name => "Great Pyrenees" },
 { :animal_type_id => dog.id, :name => "Greater Swiss Mountain Dog" },
 { :animal_type_id => dog.id, :name => "Greenland Dog" },
 { :animal_type_id => dog.id, :name => "Greyhound" },
 { :animal_type_id => dog.id, :name => "Griffon Bleu de Gascogne" },
 { :animal_type_id => dog.id, :name => "Griffon Bruxellois" },
 { :animal_type_id => dog.id, :name => "Griffon Fauve de Bretagne" },
 { :animal_type_id => dog.id, :name => "Griffon Nivernais" },
 { :animal_type_id => dog.id, :name => "Gull Dong" },
 { :animal_type_id => dog.id, :name => "Gull Terr" },
 { :animal_type_id => dog.id, :name => "Hare Indian Dog" },
 { :animal_type_id => dog.id, :name => "Hamiltonstövare" },
 { :animal_type_id => dog.id, :name => "Hanover Hound" },
 { :animal_type_id => dog.id, :name => "Harrier" },
 { :animal_type_id => dog.id, :name => "Havanese" },
 { :animal_type_id => dog.id, :name => "Hawaiian Poi Dog" },
 { :animal_type_id => dog.id, :name => "Himalayan Sheepdog" },
 { :animal_type_id => dog.id, :name => "Hokkaido" },
 { :animal_type_id => dog.id, :name => "Hortaya Borzaya" },
 { :animal_type_id => dog.id, :name => "Hovawart" },
 { :animal_type_id => dog.id, :name => "Hungarian Hound" },
 { :animal_type_id => dog.id, :name => "New Zealand Huntaway" },
 { :animal_type_id => dog.id, :name => "Hygenhund" },
 { :animal_type_id => dog.id, :name => "Ibizan Hound" },
 { :animal_type_id => dog.id, :name => "Icelandic Sheepdog" },
 { :animal_type_id => dog.id, :name => "Indian Spitz" },
 { :animal_type_id => dog.id, :name => "Irish Bull Terrier" },
 { :animal_type_id => dog.id, :name => "Irish Red and White Setter" },
 { :animal_type_id => dog.id, :name => "Irish Setter" },
 { :animal_type_id => dog.id, :name => "Irish Staffordshire Bull Terrier" },
 { :animal_type_id => dog.id, :name => "Irish Terrier" },
 { :animal_type_id => dog.id, :name => "Irish Water Spaniel" },
 { :animal_type_id => dog.id, :name => "Irish Wolfhound" },
 { :animal_type_id => dog.id, :name => "Istrian Shorthaired Hound" },
 { :animal_type_id => dog.id, :name => "Istrian Coarse-haired Hound" },
 { :animal_type_id => dog.id, :name => "Italian Greyhound" },
 { :animal_type_id => dog.id, :name => "Jack Russell Terrier" },
 { :animal_type_id => dog.id, :name => "Jagdterrier" },
 { :animal_type_id => dog.id, :name => "Jämthund" },
 { :animal_type_id => dog.id, :name => "Japanese Chin" },
 { :animal_type_id => dog.id, :name => "Japanese Spitz" },
 { :animal_type_id => dog.id, :name => "Japanese Terrier" },
 { :animal_type_id => dog.id, :name => "Jonangi" },
 { :animal_type_id => dog.id, :name => "Kaikadi" },
 { :animal_type_id => dog.id, :name => "Kai Ken" },
 { :animal_type_id => dog.id, :name => "Kangal Dog" },
 { :animal_type_id => dog.id, :name => "Kanni" },
 { :animal_type_id => dog.id, :name => "Karakachan Dog" },
 { :animal_type_id => dog.id, :name => "Karelian Bear Dog" },
 { :animal_type_id => dog.id, :name => "Karst Shepherd" },
 { :animal_type_id => dog.id, :name => "Keeshond" },
 { :animal_type_id => dog.id, :name => "Kerry Beagle" },
 { :animal_type_id => dog.id, :name => "Kerry Blue Terrier" },
 { :animal_type_id => dog.id, :name => "King Charles Spaniel" },
 { :animal_type_id => dog.id, :name => "King Shepherd" },
 { :animal_type_id => dog.id, :name => "Kintamani" },
 { :animal_type_id => dog.id, :name => "Kishu" },
 { :animal_type_id => dog.id, :name => "Komondor" },
 { :animal_type_id => dog.id, :name => "Kooikerhondje" },
 { :animal_type_id => dog.id, :name => "Koolie" },
 { :animal_type_id => dog.id, :name => "Korean Jindo Dog" },
 { :animal_type_id => dog.id, :name => "Korean Mastiff" },
 { :animal_type_id => dog.id, :name => "Kromfohrländer" },
 { :animal_type_id => dog.id, :name => "Kunming Wolf-dog" },
 { :animal_type_id => dog.id, :name => "Kur_" },
 { :animal_type_id => dog.id, :name => "Kuvasz" },
 { :animal_type_id => dog.id, :name => "Kyi-Leo" },
 { :animal_type_id => dog.id, :name => "Labrador Husky" },
 { :animal_type_id => dog.id, :name => "Labrador Retriever" },
 { :animal_type_id => dog.id, :name => "Lagotto Romagnolo" },
 { :animal_type_id => dog.id, :name => "Lakeland Terrier" },
 { :animal_type_id => dog.id, :name => "Lancashire Heeler" },
 { :animal_type_id => dog.id, :name => "Landseer" },
 { :animal_type_id => dog.id, :name => "Lapponian Herder" },
 { :animal_type_id => dog.id, :name => "Leonberger" },
 { :animal_type_id => dog.id, :name => "Lhasa Apso" },
 { :animal_type_id => dog.id, :name => "Lithuanian Hound" },
 { :animal_type_id => dog.id, :name => "Longhaired Whippet" },
 { :animal_type_id => dog.id, :name => "Lottatore Brindisino" },
 { :animal_type_id => dog.id, :name => "Löwchen" },
 { :animal_type_id => dog.id, :name => "Magyar Agár" },
 { :animal_type_id => dog.id, :name => "Majestic Tree Hound" },
 { :animal_type_id => dog.id, :name => "Maltese" },
 { :animal_type_id => dog.id, :name => "Manchester Terrier" },
 { :animal_type_id => dog.id, :name => "Maremma Sheepdog" },
 { :animal_type_id => dog.id, :name => "McNab" },
 { :animal_type_id => dog.id, :name => "Mexican Hairless Dog" },
 { :animal_type_id => dog.id, :name => "Miniature Australian Shepherd" },
 { :animal_type_id => dog.id, :name => "Miniature Fox Terrier" },
 { :animal_type_id => dog.id, :name => "Miniature Pinscher" },
 { :animal_type_id => dog.id, :name => "Miniature Schnauzer" },
 { :animal_type_id => dog.id, :name => "Miniature Siberian Husky" },
 { :animal_type_id => dog.id, :name => "Mioritic" },
 { :animal_type_id => dog.id, :name => "Molossus" },
 { :animal_type_id => dog.id, :name => "Montenegrin Mountain Hound" },
 { :animal_type_id => dog.id, :name => "Moscow Watchdog" },
 { :animal_type_id => dog.id, :name => "Moscow Water Dog" },
 { :animal_type_id => dog.id, :name => "Mountain Cur" },
 { :animal_type_id => dog.id, :name => "Mountain View Cur" },
 { :animal_type_id => dog.id, :name => "Mucuchies" },
 { :animal_type_id => dog.id, :name => "Mudi" },
 { :animal_type_id => dog.id, :name => "Mudhol Hound" },
 { :animal_type_id => dog.id, :name => "Large Münsterländer" },
 { :animal_type_id => dog.id, :name => "Small Münsterländer" },
 { :animal_type_id => dog.id, :name => "Murray River Curly Coated Retriever" },
 { :animal_type_id => dog.id, :name => "Neapolitan Mastiff" },
 { :animal_type_id => dog.id, :name => "Newfoundland" },
 { :animal_type_id => dog.id, :name => "New Guinea Singing Dog" },
 { :animal_type_id => dog.id, :name => "Norfolk Spaniel" },
 { :animal_type_id => dog.id, :name => "Norfolk Terrier" },
 { :animal_type_id => dog.id, :name => "Norrbottenspets" },
 { :animal_type_id => dog.id, :name => "North Country Beagle" },
 { :animal_type_id => dog.id, :name => "Northern Inuit Dog" },
 { :animal_type_id => dog.id, :name => "Norwegian Buhund" },
 { :animal_type_id => dog.id, :name => "Norwegian Elkhound" },
 { :animal_type_id => dog.id, :name => "Norwegian Lundehund" },
 { :animal_type_id => dog.id, :name => "Norwich Terrier" },
 { :animal_type_id => dog.id, :name => "Nova Scotia Duck-Tolling Retriever" },
 { :animal_type_id => dog.id, :name => "Old Croatian Sighthound" },
 { :animal_type_id => dog.id, :name => "Old Danish Pointer" },
 { :animal_type_id => dog.id, :name => "Old English Sheepdog" },
 { :animal_type_id => dog.id, :name => "Old English Bulldog" },
 { :animal_type_id => dog.id, :name => "Old English Terrier" },
 { :animal_type_id => dog.id, :name => "Old German Shepherd Dog" },
 { :animal_type_id => dog.id, :name => "Olde English Bulldogge" },
 { :animal_type_id => dog.id, :name => "Otterhound" },
 { :animal_type_id => dog.id, :name => "Pachon Navarro" },
 { :animal_type_id => dog.id, :name => "Paisley Terrier" },
 { :animal_type_id => dog.id, :name => "Papillon" },
 { :animal_type_id => dog.id, :name => "Parson Russell Terrier" },
 { :animal_type_id => dog.id, :name => "Patterdale Terrier" },
 { :animal_type_id => dog.id, :name => "Pekingese" },
 { :animal_type_id => dog.id, :name => "Perro de Presa Canario" },
 { :animal_type_id => dog.id, :name => "Perro de Presa Mallorquin" },
 { :animal_type_id => dog.id, :name => "Peruvian Hairless Dog" },
 { :animal_type_id => dog.id, :name => "Phalène" },
 { :animal_type_id => dog.id, :name => "Pharaoh Hound" },
 { :animal_type_id => dog.id, :name => "Picardy Spaniel" },
 { :animal_type_id => dog.id, :name => "Plott Hound" },
 { :animal_type_id => dog.id, :name => "Podenco Canario" },
 { :animal_type_id => dog.id, :name => "Pointer" },
 { :animal_type_id => dog.id, :name => "Polish Greyhound" },
 { :animal_type_id => dog.id, :name => "Polish Hound" },
 { :animal_type_id => dog.id, :name => "Polish Hunting Dog" },
 { :animal_type_id => dog.id, :name => "Polish Lowland Sheepdog" },
 { :animal_type_id => dog.id, :name => "Polish Tatra Sheepdog" },
 { :animal_type_id => dog.id, :name => "Pomeranian" },
 { :animal_type_id => dog.id, :name => "Pont-Audemer Spaniel" },
 { :animal_type_id => dog.id, :name => "Poodle" },
 { :animal_type_id => dog.id, :name => "Porcelaine" },
 { :animal_type_id => dog.id, :name => "Portuguese Podengo" },
 { :animal_type_id => dog.id, :name => "Portuguese Pointer" },
 { :animal_type_id => dog.id, :name => "Portuguese Water Dog" },
 { :animal_type_id => dog.id, :name => "Pra_sk_ Krysa_ík" },
 { :animal_type_id => dog.id, :name => "Pudelpointer" },
 { :animal_type_id => dog.id, :name => "Pug" },
 { :animal_type_id => dog.id, :name => "Puli" },
 { :animal_type_id => dog.id, :name => "Pumi" },
 { :animal_type_id => dog.id, :name => "Pungsan Dog" },
 { :animal_type_id => dog.id, :name => "Pyrenean Mastiff" },
 { :animal_type_id => dog.id, :name => "Pyrenean Shepherd" },
 { :animal_type_id => dog.id, :name => "Rafeiro do Alentejo" },
 { :animal_type_id => dog.id, :name => "Rajapalayam" },
 { :animal_type_id => dog.id, :name => "Rampur Greyhound" },
 { :animal_type_id => dog.id, :name => "Rastreador Brasileiro" },
 { :animal_type_id => dog.id, :name => "Ratonero Bodeguero Andaluz" },
 { :animal_type_id => dog.id, :name => "Rat Terrier" },
 { :animal_type_id => dog.id, :name => "Redbone Coonhound" },
 { :animal_type_id => dog.id, :name => "Rhodesian Ridgeback" },
 { :animal_type_id => dog.id, :name => "Rottweiler" },
 { :animal_type_id => dog.id, :name => "Russian Spaniel" },
 { :animal_type_id => dog.id, :name => "Russian Toy" },
 { :animal_type_id => dog.id, :name => "Russo-European Laika" },
 { :animal_type_id => dog.id, :name => "Russell Terrier" },
 { :animal_type_id => dog.id, :name => "Saarlooswolfhond" },
 { :animal_type_id => dog.id, :name => "Sabueso Español" },
 { :animal_type_id => dog.id, :name => "Sakhalin Husky" },
 { :animal_type_id => dog.id, :name => "Saluki" },
 { :animal_type_id => dog.id, :name => "Samoyed" },
 { :animal_type_id => dog.id, :name => "Sapsali" },
 { :animal_type_id => dog.id, :name => "_arplaninac" },
 { :animal_type_id => dog.id, :name => "Schapendoes" },
 { :animal_type_id => dog.id, :name => "Schillerstövare" },
 { :animal_type_id => dog.id, :name => "Schipperke" },
 { :animal_type_id => dog.id, :name => "Giant Schnauzer" },
 { :animal_type_id => dog.id, :name => "Miniature Schnauzer" },
 { :animal_type_id => dog.id, :name => "Standard Schnauzer" },
 { :animal_type_id => dog.id, :name => "Schweizer Laufhund" },
 { :animal_type_id => dog.id, :name => "Schweizerischer Niederlaufhund" },
 { :animal_type_id => dog.id, :name => "Scotch Collie" },
 { :animal_type_id => dog.id, :name => "Scottish Deerhound" },
 { :animal_type_id => dog.id, :name => "Scottish Terrier" },
 { :animal_type_id => dog.id, :name => "Sealyham Terrier" },
 { :animal_type_id => dog.id, :name => "Segugio Italiano" },
 { :animal_type_id => dog.id, :name => "Seppala Siberian Sleddog" },
 { :animal_type_id => dog.id, :name => "Serbian Hound" },
 { :animal_type_id => dog.id, :name => "Serbian Tricolour Hound" },
 { :animal_type_id => dog.id, :name => "Shar Pei" },
 { :animal_type_id => dog.id, :name => "Shetland Sheepdog" },
 { :animal_type_id => dog.id, :name => "Shiba Inu" },
 { :animal_type_id => dog.id, :name => "Shih Tzu" },
 { :animal_type_id => dog.id, :name => "Shikoku" },
 { :animal_type_id => dog.id, :name => "Shiloh Shepherd Dog" },
 { :animal_type_id => dog.id, :name => "Siberian Husky" },
 { :animal_type_id => dog.id, :name => "Silken Windhound" },
 { :animal_type_id => dog.id, :name => "Sinhala Hound" },
 { :animal_type_id => dog.id, :name => "Skye Terrier" },
 { :animal_type_id => dog.id, :name => "Sloughi" },
 { :animal_type_id => dog.id, :name => "Slovak Cuvac" },
 { :animal_type_id => dog.id, :name => "Slovakian Rough-haired Pointer" },
 { :animal_type_id => dog.id, :name => "Slovensk_ Kopov" },
 { :animal_type_id => dog.id, :name => "Smålandsstövare" },
 { :animal_type_id => dog.id, :name => "Small Greek Domestic Dog" },
 { :animal_type_id => dog.id, :name => "Soft-Coated Wheaten Terrier" },
 { :animal_type_id => dog.id, :name => "South Russian Ovcharka" },
 { :animal_type_id => dog.id, :name => "Southern Hound" },
 { :animal_type_id => dog.id, :name => "Spanish Mastiff" },
 { :animal_type_id => dog.id, :name => "Spanish Water Dog" },
 { :animal_type_id => dog.id, :name => "Spinone Italiano" },
 { :animal_type_id => dog.id, :name => "Sporting Lucas Terrier" },
 { :animal_type_id => dog.id, :name => "St. Bernard" },
 { :animal_type_id => dog.id, :name => "St. John's Water Dog" },
 { :animal_type_id => dog.id, :name => "Stabyhoun" },
 { :animal_type_id => dog.id, :name => "Staffordshire Bull Terrier" },
 { :animal_type_id => dog.id, :name => "Stephens Cur" },
 { :animal_type_id => dog.id, :name => "Styrian Coarse-haired Hound" },
 { :animal_type_id => dog.id, :name => "Sussex Spaniel" },
 { :animal_type_id => dog.id, :name => "Swedish Lapphund" },
 { :animal_type_id => dog.id, :name => "Swedish Vallhund" },
 { :animal_type_id => dog.id, :name => "Tahltan Bear Dog" },
 { :animal_type_id => dog.id, :name => "Taigan" },
 { :animal_type_id => dog.id, :name => "Tamaskan Dog" },
 { :animal_type_id => dog.id, :name => "Teddy Roosevelt Terrier" },
 { :animal_type_id => dog.id, :name => "Telomian" },
 { :animal_type_id => dog.id, :name => "Tenterfield Terrier" },
 { :animal_type_id => dog.id, :name => "Thai Bangkaew Dog" },
 { :animal_type_id => dog.id, :name => "Thai Ridgeback" },
 { :animal_type_id => dog.id, :name => "Tibetan Mastiff" },
 { :animal_type_id => dog.id, :name => "Tibetan Spaniel" },
 { :animal_type_id => dog.id, :name => "Tibetan Terrier" },
 { :animal_type_id => dog.id, :name => "Tornjak" },
 { :animal_type_id => dog.id, :name => "Tosa" },
 { :animal_type_id => dog.id, :name => "Toy Bulldog" },
 { :animal_type_id => dog.id, :name => "Toy Fox Terrier" },
 { :animal_type_id => dog.id, :name => "Toy Manchester Terrier" },
 { :animal_type_id => dog.id, :name => "Treeing Cur" },
 { :animal_type_id => dog.id, :name => "Treeing Walker Coonhound" },
 { :animal_type_id => dog.id, :name => "Tyrolean Hound" },
 { :animal_type_id => dog.id, :name => "Utonagan" },
 { :animal_type_id => dog.id, :name => "Vizsla" },
 { :animal_type_id => dog.id, :name => "Volpino Italiano" },
 { :animal_type_id => dog.id, :name => "Weimaraner" },
 { :animal_type_id => dog.id, :name => "Cardigan Welsh Corgi" },
 { :animal_type_id => dog.id, :name => "Pembroke Welsh Corgi" },
 { :animal_type_id => dog.id, :name => "Welsh Sheepdog" },
 { :animal_type_id => dog.id, :name => "Welsh Springer Spaniel" },
 { :animal_type_id => dog.id, :name => "Welsh Terrier" },
 { :animal_type_id => dog.id, :name => "West Highland White Terrier" },
 { :animal_type_id => dog.id, :name => "West Siberian Laika" },
 { :animal_type_id => dog.id, :name => "Westphalian Dachsbracke" },
 { :animal_type_id => dog.id, :name => "Wetterhoun" },
 { :animal_type_id => dog.id, :name => "Whippet" },
 { :animal_type_id => dog.id, :name => "White English Bulldog" },
 { :animal_type_id => dog.id, :name => "White Shepherd Dog" },
 { :animal_type_id => dog.id, :name => "Wirehaired Vizsla" },
 { :animal_type_id => dog.id, :name => "Wirehaired Pointing Griffon" },
 { :animal_type_id => dog.id, :name => "Yorkshire Terrier" }
])

### CAT ###############################################################################################################
Breed.create([
 { :animal_type_id => cat.id, :name => "Abyssinian" },
 { :animal_type_id => cat.id, :name => "Aegean cat" },
 { :animal_type_id => cat.id, :name => "Australian Mist" },
 { :animal_type_id => cat.id, :name => "American Polydactyl" },
 { :animal_type_id => cat.id, :name => "American Bobtail" },
 { :animal_type_id => cat.id, :name => "American Curl" },
 { :animal_type_id => cat.id, :name => "American Longhair" },
 { :animal_type_id => cat.id, :name => "American Shorthair" },
 { :animal_type_id => cat.id, :name => "American Wirehair" },
 { :animal_type_id => cat.id, :name => "Antipodean" },
 { :animal_type_id => cat.id, :name => "Asian Semi-longhair" },
 { :animal_type_id => cat.id, :name => "Balinese" },
 { :animal_type_id => cat.id, :name => "Bengal" },
 { :animal_type_id => cat.id, :name => "Birman" },
 { :animal_type_id => cat.id, :name => "Bombay" },
 { :animal_type_id => cat.id, :name => "Brazilian Shorthair" },
 { :animal_type_id => cat.id, :name => "British Shorthair" },
 { :animal_type_id => cat.id, :name => "British Longhair" },
 { :animal_type_id => cat.id, :name => "Burmese" },
 { :animal_type_id => cat.id, :name => "Burmilla" },
 { :animal_type_id => cat.id, :name => "California Spangled Cat" },
 { :animal_type_id => cat.id, :name => "Chantilly/Tiffany" },
 { :animal_type_id => cat.id, :name => "Chartreux" },
 { :animal_type_id => cat.id, :name => "Chausie" },
 { :animal_type_id => cat.id, :name => "Cheetoh" },
 { :animal_type_id => cat.id, :name => "Colorpoint Shorthair" },
 { :animal_type_id => cat.id, :name => "Cornish Rex" },
 { :animal_type_id => cat.id, :name => "Cymric" },
 { :animal_type_id => cat.id, :name => "Devon Rex" },
 { :animal_type_id => cat.id, :name => "Domestic shorthaired cat" },
 { :animal_type_id => cat.id, :name => "Donskoy" },
 { :animal_type_id => cat.id, :name => "Don Sphynx" },
 { :animal_type_id => cat.id, :name => "Dragon Li" },
 { :animal_type_id => cat.id, :name => "Egyptian Mau" },
 { :animal_type_id => cat.id, :name => "European Shorthair" },
 { :animal_type_id => cat.id, :name => "Exotic Shorthair" },
 { :animal_type_id => cat.id, :name => "German Rex" },
 { :animal_type_id => cat.id, :name => "Havana Brown" },
 { :animal_type_id => cat.id, :name => "Himalayan/Colorpoint Persian" },
 { :animal_type_id => cat.id, :name => "Japanese Bobtail" },
 { :animal_type_id => cat.id, :name => "Javanese" },
 { :animal_type_id => cat.id, :name => "Korat" },
 { :animal_type_id => cat.id, :name => "Kurilian Bobtail" },
 { :animal_type_id => cat.id, :name => "LaPerm" },
 { :animal_type_id => cat.id, :name => "Maine Coon" },
 { :animal_type_id => cat.id, :name => "Manx" },
 { :animal_type_id => cat.id, :name => "Minskin" },
 { :animal_type_id => cat.id, :name => "Munchkin" },
 { :animal_type_id => cat.id, :name => "Nebelung" },
 { :animal_type_id => cat.id, :name => "Norwegian Forest Cat" },
 { :animal_type_id => cat.id, :name => "Ocicat" },
 { :animal_type_id => cat.id, :name => "Ojos Azules" },
 { :animal_type_id => cat.id, :name => "Oregon Rex" },
 { :animal_type_id => cat.id, :name => "Oriental Bicolour" },
 { :animal_type_id => cat.id, :name => "Oriental Shorthair" },
 { :animal_type_id => cat.id, :name => "Oriental Longhair" },
 { :animal_type_id => cat.id, :name => "Persian" },
 { :animal_type_id => cat.id, :name => "Peterbald" },
 { :animal_type_id => cat.id, :name => "Pixie-bob" },
 { :animal_type_id => cat.id, :name => "Ragamuffin" },
 { :animal_type_id => cat.id, :name => "Ragdoll" },
 { :animal_type_id => cat.id, :name => "Russian Blue" },
 { :animal_type_id => cat.id, :name => "Russian White, Black and Tabby" },
 { :animal_type_id => cat.id, :name => "Savannah" },
 { :animal_type_id => cat.id, :name => "Scottish Fold" },
 { :animal_type_id => cat.id, :name => "Selkirk Rex" },
 { :animal_type_id => cat.id, :name => "Serengeti cat" },
 { :animal_type_id => cat.id, :name => "Siamese" },
 { :animal_type_id => cat.id, :name => "Siberian" },
 { :animal_type_id => cat.id, :name => "Singapura" },
 { :animal_type_id => cat.id, :name => "Snowshoe" },
 { :animal_type_id => cat.id, :name => "Sokoke" },
 { :animal_type_id => cat.id, :name => "Somali" },
 { :animal_type_id => cat.id, :name => "Sphynx" },
 { :animal_type_id => cat.id, :name => "Sumxu" },
 { :animal_type_id => cat.id, :name => "Thai/Old-style Siamese" },
 { :animal_type_id => cat.id, :name => "Tonkinese" },
 { :animal_type_id => cat.id, :name => "Toyger" },
 { :animal_type_id => cat.id, :name => "Turkish Angora" },
 { :animal_type_id => cat.id, :name => "Turkish Van" },
 { :animal_type_id => cat.id, :name => "Turkish Vankedisi" },
 { :animal_type_id => cat.id, :name => "Twisty Cat/Squitten" },
 { :animal_type_id => cat.id, :name => "Ukrainian Levkoy" },
 { :animal_type_id => cat.id, :name => "Ussuri" },
 { :animal_type_id => cat.id, :name => "wiper (USA) stripes" },
 { :animal_type_id => cat.id, :name => "York Chocolate Cat" }
])

### HORSE ##############################################################################################################
Breed.create([
 { :animal_type_id => horse.id, :name => "Abaco Barb"},
 { :animal_type_id => horse.id, :name => "Abtenauer"},
 { :animal_type_id => horse.id, :name => "Abyssinian"},
 { :animal_type_id => horse.id, :name => "Aegidienberger"},
 { :animal_type_id => horse.id, :name => "Akhal-Teke"},
 { :animal_type_id => horse.id, :name => "Albanian"},
 { :animal_type_id => horse.id, :name => "Altai"},
 { :animal_type_id => horse.id, :name => "Alter Real"},
 { :animal_type_id => horse.id, :name => "American Cream Draft"},
 { :animal_type_id => horse.id, :name => "American Indian Horse"},
 { :animal_type_id => horse.id, :name => "American Paint Horse"},
 { :animal_type_id => horse.id, :name => "American Quarter Horse"},
 { :animal_type_id => horse.id, :name => "American Saddlebred"},
 { :animal_type_id => horse.id, :name => "American Warmblood"},
 { :animal_type_id => horse.id, :name => "Andalusian Horse"},
 { :animal_type_id => horse.id, :name => "Andravida"},
 { :animal_type_id => horse.id, :name => "Anglo-Arabian"},
 { :animal_type_id => horse.id, :name => "Anglo-Arabo-Sardo"},
 { :animal_type_id => horse.id, :name => "Anglo-Kabarda"},
 { :animal_type_id => horse.id, :name => "Anglo-Norman Horse"},
 { :animal_type_id => horse.id, :name => "Appaloosa"},
 { :animal_type_id => horse.id, :name => "Appendix"},
 { :animal_type_id => horse.id, :name => "Arabian"},
 { :animal_type_id => horse.id, :name => "AraAppaloosa"},
 { :animal_type_id => horse.id, :name => "Ardennes"},
 { :animal_type_id => horse.id, :name => "Argentine Criollo"},
 { :animal_type_id => horse.id, :name => "Asturcon"},
 { :animal_type_id => horse.id, :name => "Australian Brumby"},
 { :animal_type_id => horse.id, :name => "Australian Draught Horse"},
 { :animal_type_id => horse.id, :name => "Australian Stock Horse"},
 { :animal_type_id => horse.id, :name => "Austrian Warmblood"},
 { :animal_type_id => horse.id, :name => "Auxois"},
 { :animal_type_id => horse.id, :name => "Avelignese"},
 { :animal_type_id => horse.id, :name => "Azteca"},
 { :animal_type_id => horse.id, :name => "Balearic"},
 { :animal_type_id => horse.id, :name => "Balikun"},
 { :animal_type_id => horse.id, :name => "Baluchi"},
 { :animal_type_id => horse.id, :name => "Ban'ei"},
 { :animal_type_id => horse.id, :name => "Banker Horse"},
 { :animal_type_id => horse.id, :name => "Barb"},
 { :animal_type_id => horse.id, :name => "Bashkir Curly"},
 { :animal_type_id => horse.id, :name => "Bavarian Warmblood"},
 { :animal_type_id => horse.id, :name => "Belgian"},
 { :animal_type_id => horse.id, :name => "Belgian Warmblood"},
 { :animal_type_id => horse.id, :name => "Black Forest Horse"},
 { :animal_type_id => horse.id, :name => "Blazer Horse"},
 { :animal_type_id => horse.id, :name => "Boulonnais Horse"},
 { :animal_type_id => horse.id, :name => "Brabant"},
 { :animal_type_id => horse.id, :name => "Brandenburger"},
 { :animal_type_id => horse.id, :name => "Brazilian Sport Horse"},
 { :animal_type_id => horse.id, :name => "Breton"},
 { :animal_type_id => horse.id, :name => "Brumby"},
 { :animal_type_id => horse.id, :name => "Budyonn"},
 { :animal_type_id => horse.id, :name => "Byelorussian Harness"},
 { :animal_type_id => horse.id, :name => "Calabrese"},
 { :animal_type_id => horse.id, :name => "Camargue"},
 { :animal_type_id => horse.id, :name => "Camarillo White Horse"},
 { :animal_type_id => horse.id, :name => "Campolina"},
 { :animal_type_id => horse.id, :name => "Canadian Horse"},
 { :animal_type_id => horse.id, :name => "Canadian Pacer"},
 { :animal_type_id => horse.id, :name => "Carolina Marsh Tacky"},
 { :animal_type_id => horse.id, :name => "Carthusian Horse"},
 { :animal_type_id => horse.id, :name => "Castilian Horse"},
 { :animal_type_id => horse.id, :name => "Chilean Corralero"},
 { :animal_type_id => horse.id, :name => "Chilean Horse"},
 { :animal_type_id => horse.id, :name => "Cleveland Bay"},
 { :animal_type_id => horse.id, :name => "Clydesdale"},
 { :animal_type_id => horse.id, :name => "Colonial Spanish Horse"},
 { :animal_type_id => horse.id, :name => "Comtois"},
 { :animal_type_id => horse.id, :name => "Costa Rican Saddle Horse"},
 { :animal_type_id => horse.id, :name => "Cretan"},
 { :animal_type_id => horse.id, :name => "Criollo"},
 { :animal_type_id => horse.id, :name => "Cuban Criollo"},
 { :animal_type_id => horse.id, :name => "Curly Horse"},
 { :animal_type_id => horse.id, :name => "Czech Warm Blood"},
 { :animal_type_id => horse.id, :name => "Daliboz"},
 { :animal_type_id => horse.id, :name => "Danish Warmblood"},
 { :animal_type_id => horse.id, :name => "Danube Delta Horse"},
 { :animal_type_id => horse.id, :name => "Dole Gudbrandsdal"},
 { :animal_type_id => horse.id, :name => "Don"},
 { :animal_type_id => horse.id, :name => "Dutch Heavy Draft"},
 { :animal_type_id => horse.id, :name => "Dutch Harness Horse"},
 { :animal_type_id => horse.id, :name => "Dutch Warmblood"},
 { :animal_type_id => horse.id, :name => "East Bulgarian"},
 { :animal_type_id => horse.id, :name => "East Friesian"},
 { :animal_type_id => horse.id, :name => "Estonian Draft"},
 { :animal_type_id => horse.id, :name => "Falabella"},
 { :animal_type_id => horse.id, :name => "Faroese"},
 { :animal_type_id => horse.id, :name => "Faroe"},
 { :animal_type_id => horse.id, :name => "Finnish Horse"},
 { :animal_type_id => horse.id, :name => "Fleuve"},
 { :animal_type_id => horse.id, :name => "Fjord"},
 { :animal_type_id => horse.id, :name => "Florida Cracker Horse"},
 { :animal_type_id => horse.id, :name => "Fouta"},
 { :animal_type_id => horse.id, :name => "Foutanké"},
 { :animal_type_id => horse.id, :name => "Frederiksborg"},
 { :animal_type_id => horse.id, :name => "Freiberger"},
 { :animal_type_id => horse.id, :name => "French Trotter"},
 { :animal_type_id => horse.id, :name => "Friesian Cross"},
 { :animal_type_id => horse.id, :name => "Friesian Horse"},
 { :animal_type_id => horse.id, :name => "Friesian Sporthorse"},
 { :animal_type_id => horse.id, :name => "Furioso-North Star"},
 { :animal_type_id => horse.id, :name => "Galiceno"},
 { :animal_type_id => horse.id, :name => "Galiceño"},
 { :animal_type_id => horse.id, :name => "Gelderland"},
 { :animal_type_id => horse.id, :name => "German Warmblood"},
 { :animal_type_id => horse.id, :name => "Giara's Horse"},
 { :animal_type_id => horse.id, :name => "Gidran"},
 { :animal_type_id => horse.id, :name => "Groningen Horse"},
 { :animal_type_id => horse.id, :name => "Gypsy Vanner Horse"},
 { :animal_type_id => horse.id, :name => "Hackney"},
 { :animal_type_id => horse.id, :name => "Haflinger"},
 { :animal_type_id => horse.id, :name => "Hanoverian"},
 { :animal_type_id => horse.id, :name => "Heck Horse"},
 { :animal_type_id => horse.id, :name => "Heihe"},
 { :animal_type_id => horse.id, :name => "Hispano"},
 { :animal_type_id => horse.id, :name => "Hirzai"},
 { :animal_type_id => horse.id, :name => "Holsteiner"},
 { :animal_type_id => horse.id, :name => "Hungarian Warmblood"},
 { :animal_type_id => horse.id, :name => "Icelandic Horse"},
 { :animal_type_id => horse.id, :name => "Indian Half-Bred"},
 { :animal_type_id => horse.id, :name => "Iomud"},
 { :animal_type_id => horse.id, :name => "Irish Draft"},
 { :animal_type_id => horse.id, :name => "Irish Sport Horse"},
 { :animal_type_id => horse.id, :name => "Italian Heavy Draft"},
 { :animal_type_id => horse.id, :name => "Italian Trotter"},
 { :animal_type_id => horse.id, :name => "Jutland"},
 { :animal_type_id => horse.id, :name => "Kabarda"},
 { :animal_type_id => horse.id, :name => "Kaimanawa Horse"},
 { :animal_type_id => horse.id, :name => "Karabair"},
 { :animal_type_id => horse.id, :name => "Karabakh Horse"},
 { :animal_type_id => horse.id, :name => "Karossier"},
 { :animal_type_id => horse.id, :name => "Kathiawari"},
 { :animal_type_id => horse.id, :name => "Kentucky Mountain Saddle Horse"},
 { :animal_type_id => horse.id, :name => "Kiger Mustang"},
 { :animal_type_id => horse.id, :name => "Kinsky Horse"},
 { :animal_type_id => horse.id, :name => "Kisber Felver"},
 { :animal_type_id => horse.id, :name => "Kladruber"},
 { :animal_type_id => horse.id, :name => "Knabstrup"},
 { :animal_type_id => horse.id, :name => "Konik"},
 { :animal_type_id => horse.id, :name => "Kustanair"},
 { :animal_type_id => horse.id, :name => "Latvian"},
 { :animal_type_id => horse.id, :name => "Lipizzan"},
 { :animal_type_id => horse.id, :name => "Lipizzaner"},
 { :animal_type_id => horse.id, :name => "Lithuanian Heavy Draft"},
 { :animal_type_id => horse.id, :name => "Lokai"},
 { :animal_type_id => horse.id, :name => "Lusitano"},
 { :animal_type_id => horse.id, :name => "Lyngshest"},
 { :animal_type_id => horse.id, :name => "M'Bayar"},
 { :animal_type_id => horse.id, :name => "Malapolski"},
 { :animal_type_id => horse.id, :name => "Mangalarga"},
 { :animal_type_id => horse.id, :name => "Mangalarga Marchador"},
 { :animal_type_id => horse.id, :name => "Maremmano"},
 { :animal_type_id => horse.id, :name => "Marwari"},
 { :animal_type_id => horse.id, :name => "Mecklenburger"},
 { :animal_type_id => horse.id, :name => "Messara"},
 { :animal_type_id => horse.id, :name => "Mezőhegyesi Sport-Horse"},
 { :animal_type_id => horse.id, :name => "Mezőhegyes felver"},
 { :animal_type_id => horse.id, :name => "Metis Trotter"},
 { :animal_type_id => horse.id, :name => "Miniature Horse"},
 { :animal_type_id => horse.id, :name => "Misaki"},
 { :animal_type_id => horse.id, :name => "Missouri Fox Trotter"},
 { :animal_type_id => horse.id, :name => "Moyle Horse"},
 { :animal_type_id => horse.id, :name => "Mongolian Horse"},
 { :animal_type_id => horse.id, :name => "Morab"},
 { :animal_type_id => horse.id, :name => "Morgan Horse"},
 { :animal_type_id => horse.id, :name => "Mustang"},
 { :animal_type_id => horse.id, :name => "Murakoz Horse"},
 { :animal_type_id => horse.id, :name => "Murgese"},
 { :animal_type_id => horse.id, :name => "Namib Desert Horse"},
 { :animal_type_id => horse.id, :name => "Nangchen Horse"},
 { :animal_type_id => horse.id, :name => "National Show Horse"},
 { :animal_type_id => horse.id, :name => "Nez Perce Horse"},
 { :animal_type_id => horse.id, :name => "Nokota Horse"},
 { :animal_type_id => horse.id, :name => "Noma"},
 { :animal_type_id => horse.id, :name => "Nonius"},
 { :animal_type_id => horse.id, :name => "Nordlandshest/ Lyngshest"},
 { :animal_type_id => horse.id, :name => "Noriker / Pinzgauer"},
 { :animal_type_id => horse.id, :name => "Normandy Cob"},
 { :animal_type_id => horse.id, :name => "North Swedish Horse"},
 { :animal_type_id => horse.id, :name => "Norwegian Fjord"},
 { :animal_type_id => horse.id, :name => "Novokirghiz"},
 { :animal_type_id => horse.id, :name => "Oberlander Horse"},
 { :animal_type_id => horse.id, :name => "Oldenburg"},
 { :animal_type_id => horse.id, :name => "Orlov Trotter"},
 { :animal_type_id => horse.id, :name => "Ostfriesen"},
 { :animal_type_id => horse.id, :name => "Paint Horse"},
 { :animal_type_id => horse.id, :name => "Pampa Horse"},
 { :animal_type_id => horse.id, :name => "Paso Fino"},
 { :animal_type_id => horse.id, :name => "Percheron"},
 { :animal_type_id => horse.id, :name => "Persano Horse"},
 { :animal_type_id => horse.id, :name => "Peruvian Paso"},
 { :animal_type_id => horse.id, :name => "Pleven"},
 { :animal_type_id => horse.id, :name => "Poitevin / Mulassier"},
 { :animal_type_id => horse.id, :name => "Przewalski's Horse"},
 { :animal_type_id => horse.id, :name => "Purosangue Orientale"},
 { :animal_type_id => horse.id, :name => "Qatgani"},
 { :animal_type_id => horse.id, :name => "Quarab"},
 { :animal_type_id => horse.id, :name => "Quarter Horse"},
 { :animal_type_id => horse.id, :name => "Racking Horse"},
 { :animal_type_id => horse.id, :name => "Rhenish-German Cold-Blood"},
 { :animal_type_id => horse.id, :name => "Heavy Draft"},
 { :animal_type_id => horse.id, :name => "Rhinelander"},
 { :animal_type_id => horse.id, :name => "Riwoche Horse"},
 { :animal_type_id => horse.id, :name => "Rocky Mountain Horse"},
 { :animal_type_id => horse.id, :name => "Rottaler"},
 { :animal_type_id => horse.id, :name => "Russian Don"},
 { :animal_type_id => horse.id, :name => "Russian Heavy Draft"},
 { :animal_type_id => horse.id, :name => "Russian Trotter"},
 { :animal_type_id => horse.id, :name => "Saddlebred"},
 { :animal_type_id => horse.id, :name => "Salerno"},
 { :animal_type_id => horse.id, :name => "Salerno" },
 { :animal_type_id => horse.id, :name => "San Fratello" },
 { :animal_type_id => horse.id, :name => "Sardinian" },
 { :animal_type_id => horse.id, :name => "Selle Français" },
 { :animal_type_id => horse.id, :name => "Shagya Arabian" },
 { :animal_type_id => horse.id, :name => "Shire Horse" },
 { :animal_type_id => horse.id, :name => "Siciliano indigeno" },
 { :animal_type_id => horse.id, :name => "Sorraia" },
 { :animal_type_id => horse.id, :name => "Sokolsky Horse" },
 { :animal_type_id => horse.id, :name => "Soviet Heavy Draft" },
 { :animal_type_id => horse.id, :name => "Spanish Jennet Horse" },
 { :animal_type_id => horse.id, :name => "Spanish Mustang" },
 { :animal_type_id => horse.id, :name => "Spanish Tarpan" },
 { :animal_type_id => horse.id, :name => "Spotted Saddle Horse" },
 { :animal_type_id => horse.id, :name => "Standardbred Horse" },
 { :animal_type_id => horse.id, :name => "Suffolk Punch" },
 { :animal_type_id => horse.id, :name => "Swedish Ardennes" },
 { :animal_type_id => horse.id, :name => "Swedish Warmblood" },
 { :animal_type_id => horse.id, :name => "Swiss Warmblood" },
 { :animal_type_id => horse.id, :name => "Taishuh" },
 { :animal_type_id => horse.id, :name => "Tawleed" },
 { :animal_type_id => horse.id, :name => "Tchernomor" },
 { :animal_type_id => horse.id, :name => "Tennessee Walking Horse" },
 { :animal_type_id => horse.id, :name => "Tersk Horse" },
 { :animal_type_id => horse.id, :name => "Thoroughbred" },
 { :animal_type_id => horse.id, :name => "Tinker Horse" },
 { :animal_type_id => horse.id, :name => "Tiger Horse" },
 { :animal_type_id => horse.id, :name => "Tolfetano" },
 { :animal_type_id => horse.id, :name => "Tori" },
 { :animal_type_id => horse.id, :name => "Trait Du Nord" },
 { :animal_type_id => horse.id, :name => "Trakehner" },
 { :animal_type_id => horse.id, :name => "Tuigpaard" },
 { :animal_type_id => horse.id, :name => "Ukrainian Riding Horse" },
 { :animal_type_id => horse.id, :name => "Unmol " },
 { :animal_type_id => horse.id, :name => "Uzunyayla" },
 { :animal_type_id => horse.id, :name => "Ventasso" },
 { :animal_type_id => horse.id, :name => "Virginia Highlander" },
 { :animal_type_id => horse.id, :name => "Vlaamperd" },
 { :animal_type_id => horse.id, :name => "Vladimir Heavy Draft" },
 { :animal_type_id => horse.id, :name => "Vyatka" },
 { :animal_type_id => horse.id, :name => "Waler" },
 { :animal_type_id => horse.id, :name => "Walkaloosa" },
 { :animal_type_id => horse.id, :name => "Warmblood" },
 { :animal_type_id => horse.id, :name => "Welsh Cob " },
 { :animal_type_id => horse.id, :name => "Westphalian " },
 { :animal_type_id => horse.id, :name => "Wielkopolski" },
 { :animal_type_id => horse.id, :name => "Württemberger " },
 { :animal_type_id => horse.id, :name => "Xilingol " },
 { :animal_type_id => horse.id, :name => "Yakutian " },
 { :animal_type_id => horse.id, :name => "Yili " },
 { :animal_type_id => horse.id, :name => "Yonaguni " },
 { :animal_type_id => horse.id, :name => "Zangersheide" },
 { :animal_type_id => horse.id, :name => "Zweibrücker" },
 { :animal_type_id => horse.id, :name => "Žemaitukas / Zemaituka" },
 { :animal_type_id => horse.id, :name => "Zhemaichu / Zhmudk" }
])

### RABBIT ############################################################################################################
Breed.create([
 { :animal_type_id => rabbit.id, :name => "American"},
 { :animal_type_id => rabbit.id, :name => "American Chinchilla"},
 { :animal_type_id => rabbit.id, :name => "American Fuzzy Lop"},
 { :animal_type_id => rabbit.id, :name => "American Sable"},
 { :animal_type_id => rabbit.id, :name => "Belgian Hare"},
 { :animal_type_id => rabbit.id, :name => "Beveren"},
 { :animal_type_id => rabbit.id, :name => "Blanc de Hotot"},
 { :animal_type_id => rabbit.id, :name => "Britannia Petite"}, 
 { :animal_type_id => rabbit.id, :name => "Californian"},
 { :animal_type_id => rabbit.id, :name => "Champagne d'Argent"},
 { :animal_type_id => rabbit.id, :name => "Checkered Giant"},
 { :animal_type_id => rabbit.id, :name => "Cinnamon"},
 { :animal_type_id => rabbit.id, :name => "Creme d'Argent"},
 { :animal_type_id => rabbit.id, :name => "Dutch"},
 { :animal_type_id => rabbit.id, :name => "Dwarf Hotot"},
 { :animal_type_id => rabbit.id, :name => "English Angora"},
 { :animal_type_id => rabbit.id, :name => "English Lop"},
 { :animal_type_id => rabbit.id, :name => "English Spot"},
 { :animal_type_id => rabbit.id, :name => "Flemish Giant"},
 { :animal_type_id => rabbit.id, :name => "Florida White"},
 { :animal_type_id => rabbit.id, :name => "French Angora"},
 { :animal_type_id => rabbit.id, :name => "French Lop"},
 { :animal_type_id => rabbit.id, :name => "Giant Angora"},
 { :animal_type_id => rabbit.id, :name => "Giant Chinchilla"},
 { :animal_type_id => rabbit.id, :name => "Harlequin"},
 { :animal_type_id => rabbit.id, :name => "Havana"},
 { :animal_type_id => rabbit.id, :name => "Himalayan"},
 { :animal_type_id => rabbit.id, :name => "Holland Lop"},
 { :animal_type_id => rabbit.id, :name => "Jersey Wooly"},
 { :animal_type_id => rabbit.id, :name => "Lilac"},
 { :animal_type_id => rabbit.id, :name => "Mini Lop"},
 { :animal_type_id => rabbit.id, :name => "Mini Rex"},
 { :animal_type_id => rabbit.id, :name => "Mini Satin"},
 { :animal_type_id => rabbit.id, :name => "Netherland Dwarf"},
 { :animal_type_id => rabbit.id, :name => "New Zealand"},
 { :animal_type_id => rabbit.id, :name => "Palomino"},
 { :animal_type_id => rabbit.id, :name => "Polish"},
 { :animal_type_id => rabbit.id, :name => "Rex"},
 { :animal_type_id => rabbit.id, :name => "Rhinelander"},
 { :animal_type_id => rabbit.id, :name => "Satin"},
 { :animal_type_id => rabbit.id, :name => "Satin Angora"},
 { :animal_type_id => rabbit.id, :name => "Silver"},
 { :animal_type_id => rabbit.id, :name => "Silver Fox"},
 { :animal_type_id => rabbit.id, :name => "Silver Marten"},
 { :animal_type_id => rabbit.id, :name => "Standard Chinchilla"},
 { :animal_type_id => rabbit.id, :name => "Tan"},
 { :animal_type_id => rabbit.id, :name => "Thrianta"}
])

### BIRD ##############################################################################################################
Breed.create([
 { :animal_type_id => bird.id, :name => "Budgie"},
 { :animal_type_id => bird.id, :name => "Canary"},
 { :animal_type_id => bird.id, :name => "Chicken"},
 { :animal_type_id => bird.id, :name => "Cockatiel"},
 { :animal_type_id => bird.id, :name => "Cockatoo"},
 { :animal_type_id => bird.id, :name => "Conure"},
 { :animal_type_id => bird.id, :name => "Dove"},
 { :animal_type_id => bird.id, :name => "Finch"},
 { :animal_type_id => bird.id, :name => "Lovebird"},
 { :animal_type_id => bird.id, :name => "Macaw"},
 { :animal_type_id => bird.id, :name => "Parakeet"},
 { :animal_type_id => bird.id, :name => "Parrot"},
 { :animal_type_id => bird.id, :name => "Peacock"},
 { :animal_type_id => bird.id, :name => "Pheasant"},
 { :animal_type_id => bird.id, :name => "Rosella"},
 { :animal_type_id => bird.id, :name => "Sparrow"},
 { :animal_type_id => bird.id, :name => "Toucan"},
 { :animal_type_id => bird.id, :name => "Waxbill"}
])

### REPTILE ###########################################################################################################
Breed.create([
 { :animal_type_id => reptile.id, :name => "Gecko"},
 { :animal_type_id => reptile.id, :name => "Iguana"},
 { :animal_type_id => reptile.id, :name => "Lizard"},
 { :animal_type_id => reptile.id, :name => "Snake"},
 { :animal_type_id => reptile.id, :name => "Tortoise"},
 { :animal_type_id => reptile.id, :name => "Turtle"}
])

### OTHER #############################################################################################################
Breed.create([
 { :animal_type_id => other.id, :name => "Chinchilla" },
 { :animal_type_id => other.id, :name => "Cow"},
 { :animal_type_id => other.id, :name => "Ferret"},
 { :animal_type_id => other.id, :name => "Fish"},
 { :animal_type_id => other.id, :name => "Frog"},
 { :animal_type_id => other.id, :name => "Gerbil"},
 { :animal_type_id => other.id, :name => "Goat"},
 { :animal_type_id => other.id, :name => "Guinea Pig"},
 { :animal_type_id => other.id, :name => "Hamster"},
 { :animal_type_id => other.id, :name => "Mouse"},
 { :animal_type_id => other.id, :name => "Pig"},
 { :animal_type_id => other.id, :name => "Rat"},
 { :animal_type_id => other.id, :name => "Sheep"}
])

#######################################################################################################################
#
#   NoteCategory Create
#      Creates the NoteCategories so that we have a standard set of notes
#
#######################################################################################################################
NoteCategory.create([
  { :name => "General" },
  { :name => "Medical" },
  { :name => "Behavior" }
])

# general = NoteCategory.find_by_name("General")
# medical = NoteCategory.find_by_name("Medical")
# behavior = NoteCategory.find_by_name("Behavior")
# 
# NoteCategory.create([
#   { :name => "General Test A", :parent_id => general.id },
#   { :name => "General Test B", :parent_id => general.id },
#   { :name => "Medical Test A", :parent_id => medical.id },
#   { :name => "Medical Test B", :parent_id => medical.id },
#   { :name => "Behavior Test A", :parent_id => behavior.id },
#   { :name => "Behavior Test B", :parent_id => behavior.id }
# ])

#######################################################################################################################
#
#   AlertType Create
#      Creates the AlertTypes so that we have a standard set of alert types
#
#######################################################################################################################
AlertType.create([
  { :name => "High" },
  { :name => "Medium" },
  { :name => "Low" }
])
